name: gaia
description: A new Flutter project.
version: 1.0.0+1


environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  chopper: ^3.0.0
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  flutter_auth_buttons: ^0.5.0
  flutter_hooks: ^0.6.0
  flutter_svg: ^0.14.1
  font_awesome_flutter: ^8.5.0
  google_sign_in: ^4.0.7
  http: ^0.12.0+2
  jdenticon_dart: ^1.2.1+1
  json_annotation: ^3.0.0
  shared_preferences: ^0.5.3+4
  sqflite: ^1.1.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.0
  chopper_generator: ^3.0.0
  json_serializable: ^3.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/ginger-cat/

  fonts:
    - family: Mali SemiBold
      fonts:
        - asset: assets/fonts/Mali-SemiBold.ttf
