name: gaia
description: A new Flutter project.
version: 1.0.0+1


environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+1
  flutter_hooks: ^0.2.1
  shared_preferences: ^0.5.2
  sqflite: ^1.1.5

  json_annotation: ^2.1.0

  firebase_core: ^0.3.1+1
  firebase_auth: ^0.8.2
  google_sign_in: ^4.0.1+1

  font_awesome_flutter: ^8.4.0

  jdenticon_dart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^2.1.1
  build_runner: ^1.3.1

flutter:
  uses-material-design: true

  assets:
  - assets/images/
