[default]
host = "localhost"
port = 5000

database_uri = "sqlite:///:memory:"

firebase_certificate = "gaia/config/gaia-survey-firebase-admin.json"

    [default.db]
    provider = "sqlite"
    filename = ":memory:"

[development]

[production]
